# Generated by Django 2.2.16 on 2022-05-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('Books', 'Книги'), ('Movies', 'Фильмы'), ('Music', 'Музыка')], max_length=256),
        ),
    ]
