# Generated by Django 2.2.16 on 2022-05-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220513_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('books', 'Книги'), ('movies', 'Фильмы'), ('music', 'Музыка')], max_length=256),
        ),
    ]
