# Generated by Django 2.2.16 on 2022-05-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220515_1049'),
        ('reviews', '0003_auto_20220515_1120'),
    ]

    operations = [
    ]
