# Generated by Django 2.2.16 on 2022-05-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20220517_0039'),
        ('reviews', '0006_remove_title_rating'),
    ]

    operations = [
    ]
